# Generated by Django 4.2.13 on 2024-05-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Категорію", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Назва"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описання"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="goods_images",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="Знижка в %",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Кількість"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.categories",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартири",
                "db_table": "product",
            },
        ),
    ]
