# Generated by Django 4.2.13 on 2024-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_products_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Оголошення",
                "verbose_name_plural": "Оголошення",
            },
        ),
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Площа"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.CharField(blank=True, max_length=255, verbose_name="Вулиця"),
        ),
    ]
