# Generated by Django 4.2.13 on 2024-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_products_options_alter_products_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Контактні дані"
            ),
        ),
    ]
