# Generated by Django 4.2.13 on 2024-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_products_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="products",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Номер телефону"
            ),
        ),
    ]
