# Generated by Django 4.2.13 on 2024-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_products_email_products_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Площа"
            ),
        ),
    ]
