# Generated by Django 4.2.13 on 2024-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_alter_products_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Площа"
            ),
        ),
    ]
