# Generated by Django 4.2.13 on 2024-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_alter_products_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адреса"),
        ),
    ]
