# Generated by Django 4.2.13 on 2024-05-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0011_alter_booked_options_booked_checkin_booked_checkout_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booked",
        ),
    ]
