# Generated by Django 4.2.13 on 2024-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0012_delete_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="booked_booking",
            field=models.BooleanField(
                default=False, max_length=150, verbose_name="Бронювання"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="checkin",
            field=models.DateField(default="2024-01-01", verbose_name="Дата заїзду"),
        ),
        migrations.AddField(
            model_name="products",
            name="checkout",
            field=models.DateField(default="2024-01-01", verbose_name="Дата виїзду"),
        ),
    ]
