# Generated by Django 4.2.13 on 2024-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0013_products_booked_booking_products_checkin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="rooms",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="Кімнати"
            ),
        ),
    ]
