# Generated by Django 4.2.13 on 2024-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0015_remove_products_checkin_remove_products_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="Площа"
            ),
        ),
    ]
